"""add user language and household currency

Revision ID: 42dec7773c6b
Revises: f60859b057c9
Create Date: 2026-08-17 04:15:24.548210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '42dec7773c6b'
down_revision: Union[str, Sequence[str], None] = 'f60859b057c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.Enum('toman', 'rial', 'usd', 'eur', 'aed', name='currency'), server_default='toman', nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.Enum('en', 'fa', name='language'), server_default='en', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language')

    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
